# name: Hello World Workflow

# on: push

# jobs:
#   say_hello:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print uppercase name
#         run: node -e "console.log('ANKIT KUMAR'.toUpperCase())"
